---
- name: Test connectivity to all Windows hosts
  hosts: all        # uses your inventory
  gather_facts: no
  tasks:
    - name: Ping the Windows host
      win_ping:

    - name: Check Windows version
      win_command: systeminfo
      register: system_info

    - name: Show Windows system info
      debug:
        var: system_info.stdout
