---
- name: "Disboard Windows Servers to Azure Arc-enabled "
  hosts: all
  gather_facts: true
  tasks:
    - name: Check if azcmagent binary exists (to decide if we can disconnect)
      win_stat:
        path: 'C:\Program Files\AzureConnectedMachineAgent\azcmagent.exe'
      register: arc_bin
      when: ansible_os_family == 'Windows'

    - name: Probe current connection status (optional)
      win_shell: '& "C:\Program Files\AzureConnectedMachineAgent\azcmagent.exe" show'
      register: arc_show
      failed_when: false
      changed_when: false
      when:
        - ansible_os_family == 'Windows'
        - arc_bin.stat.exists

    - name: Debug current Arc connection (optional)
      debug:
        msg: "{{ (arc_show.stdout | default('')).splitlines() }}"
      when:
        - ansible_os_family == 'Windows'
        - arc_bin.stat.exists

    - name: Disconnect existing Azure Arc connection (force + purge)
      win_shell: '& "C:\Program Files\AzureConnectedMachineAgent\azcmagent.exe" disconnect --force --purge'
      register: arc_disconnect
      changed_when: "'disconnected' in (arc_disconnect.stdout | lower) or arc_disconnect.rc == 0"
      failed_when: false
      when:
        - ansible_os_family == 'Windows'
        - arc_bin.stat.exists