---
- name: "Offboard Windows Servers from Azure Arc-enabled"
  hosts: all
  tasks:
    - name: Map azure vars to normalized names
      set_fact:
        service_principal_id: "{{ azure.AZURE_SP_ID }}"
        service_principal_secret: "{{ azure.AZURE_SP_SECRET }}"
        resource_group: "{{ azure.AZURE_RG }}"
        tenant_id: "{{ azure.AZURE_TENANT_ID }}"
        location: "{{ azure.location | default('germanywestcentral') }}"

    - name: Check if azcmagent binary exists
      ansible.windows.win_stat:
        path: 'C:\Program Files\AzureConnectedMachineAgent\azcmagent.exe'
      register: arc_bin

    - name: Show current status (pre)
      ansible.windows.win_shell: '& "C:\Program Files\AzureConnectedMachineAgent\azcmagent.exe" show'
      register: arc_show_pre
      failed_when: false
      changed_when: false
      when: arc_bin.stat.exists

    - name: Attempt graceful disconnect with service principal (delete resource)
      ansible.windows.win_shell: >
        & "C:\Program Files\AzureConnectedMachineAgent\azcmagent.exe" disconnect
        --service-principal-id "{{ azure.AZURE_SP_ID }}"
        --service-principal-secret "{{ azure.AZURE_SP_SECRET }}"
        --resource-group "{{ azure.AZURE_RG }}" 
        --tenant-id "{{ azure.AZURE_TENANT_ID }}" 
        --location "{{ azure.location }}"

      register: arc_disconnect
      when: arc_bin.stat.exists
      changed_when: >
        'disconnected' in (arc_disconnect.stdout | lower)
        or 'successfully deleted resource' in (arc_disconnect.stdout | lower)
      failed_when: false
      # no_log: true   # uncomment to hide secrets in output

    - name: Determine if remote resource deletion reported
      ansible.builtin.set_fact:
        arc_deleted_remote: "{{ 'successfully deleted resource' in (arc_disconnect.stdout | lower) }}"
      when: arc_bin.stat.exists

    - name: Post status (attempt)
      ansible.windows.win_shell: '& "C:\Program Files\AzureConnectedMachineAgent\azcmagent.exe" show'
      register: arc_show_post
      failed_when: false
      changed_when: false
      when: arc_bin.stat.exists

    - name: Discover Arc agent ProductCode (registry)
      ansible.windows.win_shell: |
        $roots = @(
          'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\*',
          'HKLM:\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\*'
        )
        foreach ($r in $roots) {
          Get-ItemProperty -Path $r -ErrorAction SilentlyContinue |
            Where-Object { $_.DisplayName -like 'Azure Connected Machine Agent*' -and $_.PSChildName -match '^\{[0-9A-Fa-f-]+\}$' } |
            Select-Object -ExpandProperty PSChildName
        }
      register: arc_product_code_raw
      changed_when: false
      failed_when: false
      when: arc_bin.stat.exists

    - name: Set product code fact
      ansible.builtin.set_fact:
        arc_product_code: "{{ (arc_product_code_raw.stdout_lines | select('match','^\\{.*\\}$') | list | first) | default('') }}"
      when: arc_bin.stat.exists

    - name: Debug found ProductCode
      ansible.builtin.debug:
        msg: "Arc agent ProductCode: {{ arc_product_code | default('NOT FOUND') }}"
      when: arc_bin.stat.exists

    - name: Uninstall Azure Arc agent (MSI product)
      ansible.windows.win_package:
        product_id: "{{ arc_product_code }}"
        state: absent
      register: arc_uninstall
      when:
        - arc_bin.stat.exists
        - arc_product_code != ''

    - name: Verify binary removal
      ansible.windows.win_stat:
        path: 'C:\Program Files\AzureConnectedMachineAgent\azcmagent.exe'
      register: arc_bin_after
      when: arc_bin.stat.exists

    - name: Remove program folder (best effort)
      ansible.windows.win_file:
        path: 'C:\Program Files\AzureConnectedMachineAgent'
        state: absent
      when: arc_product_code != ''

    - name: Remove existing MSI 
      win_file:
        path: C:\AzureConnectedMachineAgent.msi
        state: absent
      when: arc_bin.stat.exists

    - name: Summary (single-line)
      ansible.builtin.debug:
        msg: >-
          arc_offboard pre_status_present={{ arc_show_pre.stdout is defined }}
          remote_delete={{ arc_deleted_remote | default(false) }}
          purge_attempted={{ arc_purge is defined }}
          uninstall_changed={{ arc_uninstall.changed | default(false) if (arc_uninstall is defined) else false }}
          product_code="{{ arc_product_code | default('') }}"
          post_show_len={{ (arc_show_post.stdout | default('')) | length }}
    


