---
- name: "Offboard Windows Servers from Azure Arc-enabled"
  hosts: all
  tasks:
    - name: Map azure vars to normalized names
      set_fact:
        service_principal_id: "{{ azure.AZURE_SP_ID }}"
        service_principal_secret: "{{ azure.AZURE_SP_SECRET }}"
    
    - name: Check if azcmagent binary exists
      ansible.windows.win_stat:
        path: 'C:\Program Files\AzureConnectedMachineAgent\azcmagent.exe'
      register: arc_bin

    - name: Show current status (pre)
      ansible.windows.win_shell: '& "C:\Program Files\AzureConnectedMachineAgent\azcmagent.exe" show'
      register: arc_show_pre
      failed_when: false
      changed_when: false
      when: arc_bin.stat.exists

    - name: Attempt graceful disconnect with service principal (delete resource)
      ansible.windows.win_shell: >
        & "C:\Program Files\AzureConnectedMachineAgent\azcmagent.exe" disconnect
        --service-principal-id "{{ azure.AZURE_SP_ID }}"
        --service-principal-secret "{{ azure.AZURE_SP_SECRET }}"
      register: arc_disconnect
      when: arc_bin.stat.exists
      changed_when: >
        'disconnected' in (arc_disconnect.stdout | lower)
        or 'successfully deleted resource' in (arc_disconnect.stdout | lower)
      failed_when: false
      # no_log: true   # uncomment to hide secrets in output

    - name: Determine if remote resource deletion reported
      ansible.builtin.set_fact:
        arc_deleted_remote: "{{ 'successfully deleted resource' in (arc_disconnect.stdout | lower) }}"
      when: arc_bin.stat.exists

    - name: Post status (attempt)
      ansible.windows.win_shell: '& "C:\Program Files\AzureConnectedMachineAgent\azcmagent.exe" show'
      register: arc_show_post
      failed_when: false
      changed_when: false
      when: arc_bin.stat.exists

    - name: Uninstall agent if installed version is LOWER than target
      win_package:
        path: 'C:\Program Files\AzureConnectedMachineAgent\azcmagent.exe'
        state: absent
      when: arc_bin.stat.exists

    - name: Remove existing MSI prior to upgrade
      win_file:
        path: C:\AzureConnectedMachineAgent.msi
        state: absent
      when: arc_bin.stat.exists

    - name: Summary
      ansible.builtin.debug:
        msg: |
          Pre-status present: {{ (arc_show_pre.stdout is defined) }}
          Remote delete reported: {{ arc_deleted_remote | default(false) }}
          Disconnect stdout:
          {{ arc_disconnect.stdout | default('') }}
          Purge attempted: {{ arc_purge is defined }}
          Post show (raw):
          {{ arc_show_post.stdout | default('N/A') }}
    


